version: '3'
services:
  workstation:
    image: ubuntu
    container_name: user_daemon
    volumes:
    - ./:/src
    command: sleep infinity
    command: sudo add-apt-repository ppa:ethereum/ethereum
    command: sudo apt-get update
    command: sudo apt-get install solc