version: '3'
services:
  workstation:
    image: ubuntu
    container_name: user_daemon
    volumes:
    - ./:/src
    command: add-apt-repository ppa:ethereum/ethereum
    command: apt-get update
    command: apt-get install solc
    command: sleep infinity
